"""empty message

Revision ID: 2e51d44d4a90
Revises: 1746f9ed8adf
Create Date: 2021-12-12 17:36:11.975631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e51d44d4a90'
down_revision = '1746f9ed8adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spends_owner_id_fkey', 'spends', type_='foreignkey')
    op.drop_column('spends', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spends', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('spends_owner_id_fkey', 'spends', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
