"""empty message

Revision ID: 6eaa252e5764
Revises: 2e51d44d4a90
Create Date: 2021-12-12 17:47:00.868038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaa252e5764'
down_revision = '2e51d44d4a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spends', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'spends', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spends', type_='foreignkey')
    op.drop_column('spends', 'owner_id')
    # ### end Alembic commands ###
